version: '3.8'

services:
  app:
    platform: linux/amd64
    build: .
    env_file: .env
    restart: no
    volumes:
      - ./data:/app/data
      - ./characters:/app/src/characters
    working_dir: /app
    command: ["pnpm", "start", "--character=src/characters/Slime.character.json"]
